version = 1

[[annotations]]
path = [
    ".github/**",
    ".env.example"
]
precedence = "override"
SPDX-FileCopyrightText = [
    "Amsl Contributors",
]
SPDX-License-Identifier = "MIT OR Apache-2.0"

[[annotations]]
path = [
    "crates/hikari/**",
    "crates/hikari-cli/**",
    "crates/hikari-common/**",
    "CSML/components/**",
    ".gitignore",
    ".dockerignore",
    "Dockerfile",
    "Cargo.lock",
    "Cargo.toml",
    "README.md"
]
precedence = "override"
SPDX-FileCopyrightText = [
    "2022 Sven Scheu",
    "Amsl Contributors",
]
SPDX-License-Identifier = "MIT OR Apache-2.0"

[[annotations]]
path = [
    "crates/hikari-bench/**",
    "crates/hikari-config/**",
    "crates/hikari-core/**",
    "crates/hikari-db/**",
    "crates/hikari-entity/**",
    "crates/hikari-http/**",
    "crates/hikari-model/**",
    "crates/hikari-model-tools/**",
    "crates/hikari-server/**",
    "crates/hikari-test-helpers/**",
    "crates/hikari-utils/**",
    "crates/hikari-worker/**",
]
precedence = "override"
SPDX-FileCopyrightText = [
    "2023 Sven Scheu",
    "Amsl Contributors",
]
SPDX-License-Identifier = "MIT OR Apache-2.0"

[[annotations]]
path = [
    "crates/hikari-llm/**",
]
precedence = "override"
SPDX-FileCopyrightText = [
    "2023 Linus Bierhoff",
    "Amsl Contributors",
]
SPDX-License-Identifier = "MIT OR Apache-2.0"

[[annotations]]
path = [
    "rustfmt.toml"
]
precedence = "override"
SPDX-FileCopyrightText = [
    "2024 Sven Scheu",
    "Amsl Contributors",
]
SPDX-License-Identifier = "MIT OR Apache-2.0"

[[annotations]]
path = [
    "docker-compose.yml",
]
precedence = "override"
SPDX-FileCopyrightText = [
    "2024 Linus Bierhoff",
    "Amsl Contributors",
]
SPDX-License-Identifier = "MIT OR Apache-2.0"

[[annotations]]
path = [
    "crates/hikari-tools/**",
]
precedence = "override"
SPDX-FileCopyrightText = [
    "2025 Linus Bierhoff",
    "Amsl Contributors",
]
SPDX-License-Identifier = "MIT OR Apache-2.0"

[[annotations]]
path = [
    "crates/hikari-oidc/**",
    "clippy.toml",
]
precedence = "override"
SPDX-FileCopyrightText = [
    "2026 Sven Scheu",
    "Amsl Contributors",
]
SPDX-License-Identifier = "MIT OR Apache-2.0"
